// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package guardlog;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
// GUARDLOG/app/src/test/java/guardlog/AppTest.java
package guardlog;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        // Karena kelas App kita tidak memiliki metode getGreeting(),
        // baris ini harus dihapus atau dikomentari.
        // assertNotNull(classUnderTest.getGreeting(), "App should have a greeting");
        // Atau, jika Anda memang tidak membutuhkan tes ini untuk saat ini,
        // Anda bisa mengomentari seluruh metode tes ini.
        // Untuk sekarang, kita biarkan saja tes ini lulus secara default jika ada.
        System.out.println("Test: App can be instantiated.");
        assertNotNull(classUnderTest); // Memastikan objek App bisa dibuat
    }
}